version: '2'
services:
  es-master:
    image: popmessage-elasticsearch:2.4.1
    build:
      context: ./ElasticSearchCluster/elasticsearch
    volumes:
      - ./ElasticSearchCluster/elasticsearch/config/:/usr/share/elasticsearch/config
      - ./ElasticSearchCluster/elasticsearch/logs/master:/usr/share/elasticsearch/logs
      - ./ElasticSearchCluster/elasticsearch/data/master:/usr/share/elasticsearch/data
    hostname: es-master
    networks:
      es-network:
        aliases:
          - es-master.sandbox
    restart: always
    container_name: es-master
    command: /usr/share/elasticsearch/bin/elasticsearch -Enode.master=true -Ecluster.name=popmessage-es-cluster -Enode.name=master-01
  apache-proxy:
    image: apache-proxy:1.0
    build:
      context: ./ElasticSearchCluster/apache-proxy
    hostname: apache-proxy
    networks:
      es-network:
        aliases:
          - apache-proxy
    restart: always
    container_name: apache-proxy
  popmessage-api:
    image: popmessageapi
    build:
      context: ./API
    networks:
      es-network:
        aliases:
          - POPmessage
    ports:
      - "8080:8080"
    restart: always
    container_name: popmessageapi
    depends_on:
      - apache-proxy
  kibana: 
    image: kibana:5.0.1
    build:
      context: ./ElasticSearchCluster/kibana
    ports:
      - "17561:5601"
    networks:
      - es-network
    volumes:
      - ./ElasticSearchCluster/kibana/config/:/opt/kibana/config/
    environment:
      - ELASTICSEARCH_URL=http://es-master:9200
    container_name: kibana
  es-node1:
    image: popmessage-elasticsearch:2.4.1
    build:
      context: ./ElasticSearchCluster/elasticsearch
    volumes:
      - ./ElasticSearchCluster/elasticsearch/config/:/usr/share/elasticsearch/config
      - ./ElasticSearchCluster/elasticsearch/logs/node-1:/usr/share/elasticsearch/logs
      - ./ElasticSearchCluster/elasticsearch/data/node-1:/usr/share/elasticsearch/data
    networks:
      - es-network
    restart: always
    command: /usr/share/elasticsearch/bin/elasticsearch -Enode.master=false -Ecluster.name=popmessage-es-cluster -Ediscovery.zen.ping.unicast.hosts=es-master
    container_name: es-node_1
    depends_on:
      - es-master
  es-node2:
    image: popmessage-elasticsearch:2.4.1
    build:
      context: ./ElasticSearchCluster/elasticsearch
    volumes:
      - ./ElasticSearchCluster/elasticsearch/config/:/usr/share/elasticsearch/config
      - ./ElasticSearchCluster/elasticsearch/logs/node-2:/usr/share/elasticsearch/logs
      - ./ElasticSearchCluster/elasticsearch/data/node-2:/usr/share/elasticsearch/data
    networks:
      - es-network
    restart: always
    command: /usr/share/elasticsearch/bin/elasticsearch -Enode.master=false -Ecluster.name=popmessage-es-cluster -Ediscovery.zen.ping.unicast.hosts=es-master
    container_name: es-node_2
    depends_on:
      - es-master
  es-node3:
    image: popmessage-elasticsearch:2.4.1
    build:
      context: ./ElasticSearchCluster/elasticsearch
    volumes:
      - ./ElasticSearchCluster/elasticsearch/config/:/usr/share/elasticsearch/config
      - ./ElasticSearchCluster/elasticsearch/logs/node-3:/usr/share/elasticsearch/logs
      - ./ElasticSearchCluster/elasticsearch/data/node-3:/usr/share/elasticsearch/data
    networks:
      - es-network
    restart: always
    command: /usr/share/elasticsearch/bin/elasticsearch -Enode.master=false -Ecluster.name=popmessage-es-cluster -Ediscovery.zen.ping.unicast.hosts=es-master
    container_name: es-node_3
    depends_on:
      - es-master

networks:
  es-network:
    driver: bridge
